### ISSUE TITLE
Markdown practice post...

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/psy1903-forum#2]
Post your solution to the Markdown practice exercise here...
(Details in this exercise can be found in the Week 1 Task Set)

**Comment by AmberSimons1** [comment]
My name is **Amber** and I am from _Needville, TX_!

Three books I've enjoyed recently are 

+ [Fingersmith by Sarah Waters](https://en.wikipedia.org/wiki/Fingersmith_(novel))
+ [The House in the Cerulean Sea by TJ Klune](https://www.amazon.com/House-Cerulean-Sea-TJ-Klune/dp/1250217288)
+ [The Power by Naomi Alderman](https://en.wikipedia.org/wiki/The_Power_(Alderman_novel))



```js
function generateRandomLetters(length) {
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
    let result = '';
    for (let i = 0; i < length; i++) {
        const randomIndex = Math.floor(Math.random() * alphabet.length);
        result += alphabet[randomIndex];
    }
    return result;
}

document.write(generateRandomLetters(5));
```

**Comment by JuliusNagin** [comment]
My name is **Julius** and I am from _Cambridge, MA._

Three books I've enjoyed recently are:
+ [Kindred](https://en.wikipedia.org/wiki/Kindred_(novel)) by Octavia Butler
+ [Beloved](https://en.wikipedia.org/wiki/Beloved_(novel)) by Toni Morrison
+ [The Short-Timers](https://en.wikipedia.org/wiki/The_Short-Timers) by Gustav Hasford

```js
function generateRandomLetters(length) {
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
    let result = '';
    for (let i = 0; i < length; i++) {
        const randomIndex = Math.floor(Math.random() * alphabet.length);
        result += alphabet[randomIndex];
    }
    return result;
}

document.write(generateRandomLetters(5));
```

**Comment by joanne-ji** [comment]
Hi! My name is **Jae**, and I'm from *Leonia, NJ*.

Three books that I've enjoyed recently are:

- [*The Buddha in the Attic* by Julie Otsuka](https://en.wikipedia.org/wiki/The_Buddha_in_the_Attic)
- [*Bitter* by Akwaeke Emezi](https://en.wikipedia.org/wiki/Bitter_(novel))
- [*Long Way Down* by Jason Reynolds](https://en.wikipedia.org/wiki/Long_Way_Down_(book))

```js
function generateRandomLetters(length) {
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
    let result = '';
    for (let i = 0; i < length; i++) {
        const randomIndex = Math.floor(Math.random() * alphabet.length);
        result += alphabet[randomIndex];
    }
    return result;
}

document.write(generateRandomLetters(5));
```

**Comment by katiearrambide** [comment]
Hi! My name is **Katie Arrambide** and I am from *St. Charles, Illinois*

3 books I've enjoyed recently are:

- [Everything I Know About Love](https://www.amazon.com/Everything-Know-About-Love-Memoir/dp/0062968793)
- [The Secret Lives of Introverts](https://www.amazon.com/Secret-Lives-Introverts-Inside-Hidden/dp/1510721029/ref=asc_df_1510721029/?tag=hyprod-20&linkCode=df0&hvadid=693308329663&hvpos=&hvnetw=g&hvrand=9583426739286600758&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9002000&hvtargid=pla-348206802710&psc=1&mcid=e441675f1d3d38808b17d26d7ce320f5)
- [Nudge](https://www.amazon.com/Nudge-Improving-Decisions-Health-Happiness/dp/014311526X)

```js
function generateRandomLetters(length) {
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
    let result = '';
    for (let i = 0; i < length; i++) {
        const randomIndex = Math.floor(Math.random() * alphabet.length);
        result += alphabet[randomIndex];
    }
    return result;
}

document.write(generateRandomLetters(5));

**Comment by sylviatraw** [comment]
My name is **Sylvia** and I am from _Youngstown, OH_

Three books I've enjoyed recently are:
+ [A Court of Mist and Fury](https://www.goodreads.com/book/show/50659468-a-court-of-mist-and-fury)
+ [I must Betray You](https://www.goodreads.com/book/show/56970272-i-must-betray-you)
+ [Caste: The Origins of Our Discontents](https://www.amazon.com/Caste-Origins-Discontents-Isabel-Wilkerson/dp/0593230256)

```js
function generateRandomLetters(length) {
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
    let result = '';
    for (let i = 0; i < length; i++) {
        const randomIndex = Math.floor(Math.random() * alphabet.length);
        result += alphabet[randomIndex];
    }
    return result;
}

document.write(generateRandomLetters(5));
```

**Comment by stephaniezaragoza18** [comment]
My name is **Stephanie** and I am from _Aiken, South Carolina._

Three books I have enjoyed recently are:
+ [A Court of Thorns and Roses](https://en.wikipedia.org/wiki/A_Court_of_Thorns_and_Roses)
+ [The Song of Achilles](https://en.wikipedia.org/wiki/The_Song_of_Achilles)
+ [The Midnight Library](https://en.wikipedia.org/wiki/The_Midnight_Library)


```js
function generateRandomLetters(length) {
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
    let result = '';
    for (let i = 0; i < length; i++) {
        const randomIndex = Math.floor(Math.random() * alphabet.length);
        result += alphabet[randomIndex];
    }
    return result;
}

document.write(generateRandomLetters(5));
```

**Comment by ashkim1** [comment]
My name is **Ash** and I am from _Ellicott City, MD_.

Here are three books I've enjoyed recently:
+ [An Unquiet Mind](https://en.wikipedia.org/wiki/An_Unquiet_Mind) by Kay Redfield Jamison
+ [Many Lives, Many Masters](https://www.brianweiss.com/about-the-books/many-lives-many-masters/) by Brian L. Weiss, M.D.
+ [On Earth We're Briefly Gorgeous](https://en.wikipedia.org/wiki/On_Earth_We%27re_Briefly_Gorgeous) by Ocean Vuong

```js
function generateRandomLetters(length) {
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
    let result = '';
    for (let i = 0; i < length; i++) {
        const randomIndex = Math.floor(Math.random() * alphabet.length);
        result += alphabet[randomIndex];
    }
    return result;
}

document.write(generateRandomLetters(5));
```

**Comment by kaya-vadhan** [comment]
I'm **Kaya** from _Brookline, Massachusetts._

I've enjoyed reading the books:
- [The Talented Mr. Ripley](https://en.wikipedia.org/wiki/The_Talented_Mr._Ripley) by Patricia Highsmith
- [Talking to Strangers](https://en.wikipedia.org/wiki/Talking_to_Strangers) by Malcolm Gladwell
- [American Psycho](https://en.wikipedia.org/wiki/American_Psycho) by Bret Easton Ellis

```js
function generateRandomLetters(length) {
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
    let result = '';
    for (let i = 0; i < length; i++) {
        const randomIndex = Math.floor(Math.random() * alphabet.length);
        result += alphabet[randomIndex];
    }
    return result;
}

document.write(generateRandomLetters(5));
```

**Comment by seangallagher26** [comment]
Hi! My name is **Sean** and I'm from _Burlington, MA_

Three books I've enjoyed recently are:

+ [Biased](https://www.amazon.com/Biased-Uncovering-Hidden-Prejudice-Shapes/dp/0735224951/ref=sr_1_1?crid=WAMHRBPB0KJN&dib=eyJ2IjoiMSJ9.LB88GLRwrm0qR9__IEn29XwKW3p_RjGr-4rcCgPR_eIxC-Y9zZpLlfffz0PrMA0EDYOQUqdkwiPld_ghsLuz9SOuB_YOO3LXV47aHO4RFHymRdrDOt1Kni0nHMdiBKR2K6sk-ncbOT73DbDuvVjSgUP23CLU8qg0GZmtxyl9mfNk4ZkG63VY_0zyTOyT19s1lW4q8_WbsxpV05lqkMb2AqF3Fk5YWeX_TrWoTkSg5_A.GY3SONYZ5mEJ0otfTSLpTtiMv9hiJs8clRNVtgA_ChA&dib_tag=se&keywords=biased&qid=1725396488&sprefix=biase%2Caps%2C193&sr=8-1) by Jennifer Eberhardt
+ [The Color Purple](https://en.wikipedia.org/wiki/The_Color_Purple) by Alice Walker
+ [Scythe](https://en.wikipedia.org/wiki/Scythe_(novel)) by Neal Shusterman

```js
function generateRandomLetters(length) {
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
    let result = '';
    for (let i = 0; i < length; i++) {
        const randomIndex = Math.floor(Math.random() * alphabet.length);
        result += alphabet[randomIndex];
    }
    return result;
}

document.write(generateRandomLetters(5));
```

**Comment by gbenkelman** [comment]
My name is **Grace** and I'm from _Whitefish, Montana_

I've enjoyed these books recently:

+ [Outliers](https://www.amazon.com/Outliers-Story-Success-Malcolm-Gladwell/dp/0316017930) by Malcom Gladwell
+ [Gunfight](https://www.amazon.com/Gunfight-Against-Industry-Radicalized-America/dp/1541768736) by Ryan Busse
+ [We Were Liars](https://www.amazon.com/We-Were-Liars-Lockhart/dp/038574126X) by E. Lockhart

**Comment by kjsauce** [comment]
I'm **Kayla** and I'm from _El Paso, Texas_. 
Three books I've enjoyed recently are: 
+ [What My Bones Know](https://www.amazon.com/What-My-Bones-Know-Healing/dp/0593238125/ref=asc_df_0593238125/?tag=hyprod-20&linkCode=df0&hvadid=693272947578&hvpos=&hvnetw=g&hvrand=14937286915802307570&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9001999&hvtargid=pla-1917245051500&psc=1&mcid=c740f96e0dc232358a34603fd23400c1) by Stephanie Foo
+ [The Haunting of Hill House](https://www.amazon.com/Haunting-Hill-House-Shirley-Jackson-ebook/dp/B0D83LBPJ8/ref=sr_1_1?crid=3DQXA0WUES3NY&dib=eyJ2IjoiMSJ9.7-60tGoO6fAlOnr5aNdUppYWYsm8zvtDX-yQDIjuIu3Fuem3HTBvq6VV_qUZ7DwkKANEuQt5dot22gKiBpiDvzR9enmTXUEdUUpzdpy_NDxXnjRmF2qdd_FibjtZQMAfifA4WYRjA1wVQpOrkhNIDot7w1WhmybUdThmRyr3ONk9w8If8_Zya8bHZHSZ8CbquP8KbIwskztkte4kHTU3mLNJjNGHlqD2WSeuUYTC_o0.HH9cf_LwGPzwWSq7fQTrAE7G02E2VNHdM_CZP5EIvAA&dib_tag=se&keywords=haunting+of+hill+house&qid=1725397147&s=books&sprefix=haunting+of+hill+house%2Cstripbooks%2C69&sr=1-1) by Shirley Jackson 
+ [Normal People](https://www.amazon.com/Normal-People-Novel-Sally-Rooney/dp/1984822187/ref=sr_1_1?crid=1MTD3PLUWPB35&dib=eyJ2IjoiMSJ9.QODyhp9LMcy88GeH58LGrM3Uhs68j0Qm_JaA442Lt-idvdQgCUZGoq-jRNq8Z3Z6xN4jyOkH6Gvczi8N7n0krB1kOftcd215D05guv1aiyxxCUgaLbvCKwTRchDf5LGZKDExqDJHATtMLn2bEaCt5VVTKYSaTFAqrg99nMYMYF_0NBx9QNJs-DP9fuvHkE6epiE7TAprGh7-M9wodVS5QUWIyO1rG1QloGKPcxMoaEw.ohTkrapMD-2b1_0laohLXs8PNtRQXWQq3d-TF0JS9T8&dib_tag=se&keywords=normal+people&qid=1725397170&s=books&sprefix=normal+people%2Cstripbooks%2C71&sr=1-1) by Sally Rooney

```js 
function generateRandomLetters(length) {
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
    let result = '';
    for (let i = 0; i < length; i++) {
        const randomIndex = Math.floor(Math.random() * alphabet.length);
        result += alphabet[randomIndex];
    }
    return result;
}

document.write(generateRandomLetters(5));

**Comment by gbenkelman** [comment]
My name is **Grace** and I'm from _Whitefish, Montana_

I've enjoyed these books recently! 

+ [Outliers](https://www.amazon.com/Outliers-Story-Success-Malcolm-Gladwell/dp/0316017930) by Malcom Gladwell
+ [We Were Liars](https://www.amazon.com/We-Were-Liars-Lockhart/dp/038574126X) by E. Lockhart
+ [Gunfight](https://www.amazon.com/Gunfight-Against-Industry-Radicalized-America-ebook/dp/B09533PRXJ/ref=sr_1_1?crid=34HUIUJCAZ1I3&dib=eyJ2IjoiMSJ9.1-z8EzvzdHU1DFjFcRAtSF1uFbTDX_VncLOQIcMSxOYrnrXAGMigu5jOZUwh97CWohkONXiMslPldjWDUlBbXQsI77TumjEeqNOFZiLrIpGt9MzD9m691QC_4w-i3InoMl6j67jTQsr6FjhHctKm5hKkmufaYVH-4DnCsv_Km84d0uMSGZp6-sd9RTjRA_3aodcR1H9koD453OgIzkJIboNJ729rlitYmuS8PlRdvWjZXRuJQcr7kSnQjWIQhV7tggyoN9sE0mjB6loQv4QN1mRWOY9KrRB4SWTM-rIjOMo.SMGqY5GBhVjxO7F3L9XsMCGEPFAtqeln9WeEKxULc3o&dib_tag=se&keywords=gunfight&qid=1725398332&s=books&sprefix=gunfight%2Cstripbooks%2C70&sr=1-1) by Ryan Busse

```js

function generateRandomLetters(length) {
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
    let result = '';
    for (let i = 0; i < length; i++) {
        const randomIndex = Math.floor(Math.random() * alphabet.length);
        result += alphabet[randomIndex];
    }
    return result;
}

document.write(generateRandomLetters(5));
```

**Comment by nycollycarvalho** [comment]
My name is **Nycolly** and I'm from _Porto Alegre, Brazil_.

Here are three books I've enjoyed recently: 

+ [A natureza da mordida](https://www.amazon.com/natureza-mordida-Em-Portugues-Brasil/dp/6555872233) by Carla Madeira 
+ [Restless](https://www.amazon.com/Reckless-Powerless-Trilogy-Lauren-Roberts/dp/1665955430/ref=sr_1_1?crid=1T0DRLDAC1G0&dib=eyJ2IjoiMSJ9.0pjD9W_5aKh_zeYh8_WeUDI59BJmfO3OZekhMavdsIMPcCxEUJ7mse-Ls5NQ6in_.zdDeRnaP6ZhFvJ3FDpKRpFSOLUqF55fz996-dfWFDEA&dib_tag=se&keywords=restless+lauren+roberts&qid=1725480982&sprefix=restless+lauren%2Caps%2C95&sr=8-1&ccs_id=606f5f92-393b-43ec-b619-c3798750a15b) by Lauren Roberts
+ [Conversations with friends](https://www.amazon.com/Conversations-Friends-Novel-Sally-Rooney/dp/0451499069/ref=sr_1_1?crid=WYG7FKVIASZH&dib=eyJ2IjoiMSJ9.ZhPtzuQF3A5zCAqvySxVqw-D9BHeB5A-pFGmYFTd2XnsXdthMXNEYl3VR3O2UgfCXang2CqrXcnOoYBV_HGmqNEyZqCKuKaZR0CTvDxbrAkrcH3dTFQXxOlcv7R_8_dsCTKNsqsuah9LXeKLF_fFG1dN_MZVZ5hT7MB9wgsF_b2wsV_Sz2La222y-M1U8K6SuzCYbMyh6iQGsiqTS-CO1a4e-Ic3hrbQpNvh40-yFbk.dFVuKkzj3aNaT7btskF7PLYOfeLs4jvOHMZKV18pPqg&dib_tag=se&keywords=conversations+with+friends&qid=1725481166&s=books&sprefix=conversa%2Cstripbooks%2C86&sr=1-1) by Sally Rooney

```js
function generateRandomLetters(length) {
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
    let result = '';
    for (let i = 0; i < length; i++) {
        const randomIndex = Math.floor(Math.random() * alphabet.length);
        result += alphabet[randomIndex];
    }
    return result;
}

document.write(generateRandomLetters(5));```

**Comment by nycollycarvalho** [comment]
My name is **Nycolly** and I'm from _Porto Alegre, Brazil_.

Here are three books I've enjoyed recently: 

+ [A natureza da mordida](https://www.amazon.com/natureza-mordida-Em-Portugues-Brasil/dp/6555872233) by Carla Madeira 
+ [Restless](https://www.amazon.com/Reckless-Powerless-Trilogy-Lauren-Roberts/dp/1665955430/ref=sr_1_1?crid=1T0DRLDAC1G0&dib=eyJ2IjoiMSJ9.0pjD9W_5aKh_zeYh8_WeUDI59BJmfO3OZekhMavdsIMPcCxEUJ7mse-Ls5NQ6in_.zdDeRnaP6ZhFvJ3FDpKRpFSOLUqF55fz996-dfWFDEA&dib_tag=se&keywords=restless+lauren+roberts&qid=1725480982&sprefix=restless+lauren%2Caps%2C95&sr=8-1&ccs_id=606f5f92-393b-43ec-b619-c3798750a15b) by Lauren Roberts
+ [Conversations with friends](https://www.amazon.com/Conversations-Friends-Novel-Sally-Rooney/dp/0451499069/ref=sr_1_1?crid=WYG7FKVIASZH&dib=eyJ2IjoiMSJ9.ZhPtzuQF3A5zCAqvySxVqw-D9BHeB5A-pFGmYFTd2XnsXdthMXNEYl3VR3O2UgfCXang2CqrXcnOoYBV_HGmqNEyZqCKuKaZR0CTvDxbrAkrcH3dTFQXxOlcv7R_8_dsCTKNsqsuah9LXeKLF_fFG1dN_MZVZ5hT7MB9wgsF_b2wsV_Sz2La222y-M1U8K6SuzCYbMyh6iQGsiqTS-CO1a4e-Ic3hrbQpNvh40-yFbk.dFVuKkzj3aNaT7btskF7PLYOfeLs4jvOHMZKV18pPqg&dib_tag=se&keywords=conversations+with+friends&qid=1725481166&s=books&sprefix=conversa%2Cstripbooks%2C86&sr=1-1) by Sally Rooney

```js
function generateRandomLetters(length) {
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
    let result = '';
    for (let i = 0; i < length; i++) {
        const randomIndex = Math.floor(Math.random() * alphabet.length);
        result += alphabet[randomIndex];
    }
    return result;
}

document.write(generateRandomLetters(5));
```

**Comment by wendycv02** [comment]
My name is **Wendy** and I am originally from _El Salvador_:

Here are three books I've enjoyed:
+ [_The Picture of Dorian Gray_](https://en.wikipedia.org/wiki/The_Picture_of_Dorian_Gray) by Oscar Wilde 
+ [_Daughter of Smoke and Bone_](https://en.wikipedia.org/wiki/Daughter_of_Smoke_and_Bone) by Laini Taylor 
+ [_The Little Prince_](https://en.wikipedia.org/wiki/The_Little_Prince) by Antoine de Saint-Exupéry

```js
function generateRandomLetters(length) {
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
    let result = '';
    for (let i = 0; i < length; i++) {
        const randomIndex = Math.floor(Math.random() * alphabet.length);
        result += alphabet[randomIndex];
    }
    return result;
}

document.write(generateRandomLetters(5));
}
