### ISSUE TITLE
Anyone else having an issue with consistent "This site can’t be reached" messages in browser?

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/psy1903-forum#5]
Hi all,

One of your classmates is having an issue where after making changes to files and switching to the browser to see their changes, they are unable to load the page and see the output _"This site can’t be reached"_ (screenshot below.).

This continues to happen for 10-20 seconds, but eventually after refreshing multiple times things eventually load.

As you can imagine, this makes development very frustrating because there's a 10-20 second gap anytime you want to test some change.

**Has anyone else experienced this issue? I'm trying to collect more data on the problem to narrow down what might be causing it.**

<img width="672" alt="image" src="https://github.com/user-attachments/assets/4c15c2d2-6709-45ab-a56f-f4c5981beb67">

**Comment by gbenkelman** [comment]
I have not been able to see or download anything from the image link

**Comment by susanBuck** [comment]
Hi @gbenkelman - Which image link are you referring to?

**Comment by gbenkelman** [comment]
Oh wait no -- I am trying to download the image using the link for the last question and it brings me to a page that says the site can't be reached

**Comment by gbenkelman** [comment]
[this image: facial-expression-1-incongruent.pngLinks to an external site.](https://psy1903.com.test/images/content/facial-expression-1-incongruent.png)

**Comment by susanBuck** [comment]
Gotcha! To fix that, update the url

Before:

https://psy1903.com.test/images/content/facial-expression-1-incongruent.png

After (remove .test):

https://psy1903.com/images/content/facial-expression-1-incongruent.png

(I updated this in the assignment in Canvas but you might be seeing an older version still)

**Comment by gbenkelman** [comment]
thank you!!
