### ISSUE TITLE
Confusion about operator practice problem #3

### ISSUE THREAD

**Issue by sylviatraw** [susanBuck/psy1903-forum#7]
My code for this expression is console.log(20 > 15 < 15); and it outputs as _true_ but I don't understand why it is _true_ when 15 is not less than 15. This might just be a basic math confusion but I'm confused nonetheless lol

**Comment by susanBuck** [comment]
Great question! It has to do with the fact that when we treat boolean values as numbers in JavaScript, `true` translates to `1` (and `false` translates to `0`).

So reading the statement left to right, `20 > 15` is `true`.

Then `true < 15` is interpreted as `1 < 15` which is `true`, making the overall statement `true`.

Let us know if you have any follow-up questions on this!
